// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppli.Models;

namespace WebAppli.Migrations
{
    [DbContext(typeof(CRMContext))]
    [Migration("20200101124235_2.0")]
    partial class _20
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppli.Models.Addupto", b =>
                {
                    b.Property<int>("Aid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Agid")
                        .HasColumnType("int");

                    b.Property<string>("Aoid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AsumN")
                        .HasColumnType("int");

                    b.HasKey("Aid");

                    b.ToTable("Addupto");
                });

            modelBuilder.Entity("WebAppli.Models.Goods", b =>
                {
                    b.Property<int>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Gdescribe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gimg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gint")
                        .HasColumnType("int");

                    b.Property<int?>("Ginventory")
                        .HasColumnType("int");

                    b.Property<string>("Gname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gprice")
                        .HasColumnType("int");

                    b.Property<string>("Gstring")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gsum")
                        .HasColumnType("int");

                    b.Property<int?>("Gtai")
                        .HasColumnType("int");

                    b.Property<int?>("Gtype")
                        .HasColumnType("int");

                    b.HasKey("Gid");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("WebAppli.Models.Location", b =>
                {
                    b.Property<int>("Lid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Lname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lonation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lphone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Lid");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("WebAppli.Models.Merchant", b =>
                {
                    b.Property<int>("Mid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mimg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mpwd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Msite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mweixin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mid");

                    b.ToTable("Merchant");
                });

            modelBuilder.Entity("WebAppli.Models.Orderform", b =>
                {
                    b.Property<int>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Alid")
                        .HasColumnType("int");

                    b.Property<int?>("Aowid")
                        .HasColumnType("int");

                    b.Property<string>("Orders")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Oshou")
                        .HasColumnType("int");

                    b.Property<DateTime>("Otime")
                        .HasColumnType("datetime2");

                    b.HasKey("Oid");

                    b.ToTable("Orderform");
                });

            modelBuilder.Entity("WebAppli.Models.Shopping", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Sgid")
                        .HasColumnType("int");

                    b.Property<int?>("Shu")
                        .HasColumnType("int");

                    b.HasKey("Sid");

                    b.ToTable("Shopping");
                });

            modelBuilder.Entity("WebAppli.Models.TypeGoods", b =>
                {
                    b.Property<int>("Tid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tstring")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Tid");

                    b.ToTable("TypeGoods");
                });
#pragma warning restore 612, 618
        }
    }
}
